# Generated by Django 3.1.6 on 2022-02-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='sub_cate',
            field=models.CharField(default='', max_length=100),
        ),
    ]
